/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.io.File

fun main() {
    File("input").listFiles()?.sortedBy { it.name }?.forEachIndexed { index, file ->
        val input = file.readText()
        val output = execute(input)
        printOutput(output, index)
    }
}

fun execute(input: String): String {
    return InputProcessor.proccess(input)
}

fun printOutput(output: String, index: Int) =
    File("output/outputFile$index").writeText(output)